import { NextResponse } from "next/server";
import { db } from "@/lib/db";

// Audit log retention: 90 days
// Call this endpoint via cron (e.g., daily) or manually
// Protected by a secret key to prevent unauthorized access
export async function POST(request: Request) {
  const authHeader = request.headers.get("authorization");
  const expectedKey = process.env.CRON_SECRET;

  if (!expectedKey) {
    console.error("[CLEANUP] CRON_SECRET environment variable is not set");
    return NextResponse.json({ error: "Server misconfiguration" }, { status: 500 });
  }

  if (authHeader !== `Bearer ${expectedKey}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const retentionDays = 90;
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - retentionDays);

  // Delete audit logs older than retention period
  const deletedLogs = await db.auditLog.deleteMany({
    where: { createdAt: { lt: cutoff } },
  });

  // Delete expired/used password reset tokens (older than 24 hours)
  const tokenCutoff = new Date(Date.now() - 24 * 60 * 60 * 1000);
  const deletedTokens = await db.passwordResetToken.deleteMany({
    where: {
      OR: [
        { expires: { lt: new Date() } },
        { used: true, createdAt: { lt: tokenCutoff } },
      ],
    },
  });

  // Auto-activate approved challenges whose start date has arrived
  const activated = await db.challenge.updateMany({
    where: {
      status: "APPROVED",
      startDate: { lte: new Date() },
      endDate: { gt: new Date() },
    },
    data: { status: "ACTIVE", isActive: true },
  });

  // Auto-complete active challenges whose end date has passed
  const completed = await db.challenge.updateMany({
    where: {
      status: "ACTIVE",
      endDate: { lt: new Date() },
    },
    data: { status: "COMPLETED", isActive: false },
  });

  // Auto-generate next month's challenges (idempotent - safe to run daily)
  let autoGeneratedCount = 0;
  const autoGenSetting = await db.appSetting.findUnique({
    where: { key: "challenge_auto_generate_enabled" },
  });

  if (autoGenSetting?.value === "true") {
    const now = new Date();
    const nextMonthStart = new Date(now.getFullYear(), now.getMonth() + 1, 1);
    const nextMonthEnd = new Date(now.getFullYear(), now.getMonth() + 2, 0);
    const nextMonthName = nextMonthStart.toLocaleString("en-GB", { month: "long" });

    const templates = await db.challengeTemplate.findMany({
      where: { isEnabled: true },
    });

    for (const template of templates) {
      // Skip if a challenge already exists for this category starting next month or later
      const existing = await db.challenge.findFirst({
        where: {
          category: template.category,
          startDate: { gte: nextMonthStart },
        },
      });

      if (!existing) {
        await db.challenge.create({
          data: {
            title: template.titlePattern.replace("{month}", nextMonthName),
            description: template.description
              .replace("{month}", nextMonthName)
              .replace("{target}", String(template.targetValue)),
            category: template.category,
            targetValue: template.targetValue,
            startDate: nextMonthStart,
            endDate: nextMonthEnd,
            status: "PENDING_REVIEW",
            isActive: false,
          },
        });
        autoGeneratedCount++;
      }
    }
  }

  return NextResponse.json({
    success: true,
    deletedAuditLogs: deletedLogs.count,
    deletedTokens: deletedTokens.count,
    activatedChallenges: activated.count,
    completedChallenges: completed.count,
    autoGeneratedChallenges: autoGeneratedCount,
    retentionDays,
  });
}
